import { NextResponse } from "next/server";
import nodemailer from "nodemailer";
import { z, ZodError } from "zod";

const formSchema = z.object({
  firstName: z.string().min(2).max(50),
  lastName: z.string().min(2).max(50),
  email: z.string().email(),
  interest: z.string().min(10).max(500),
});

export async function POST(req: Request) {
  try {
    const json = await req.json();
    const parsed = formSchema.parse(json);

    const { firstName, lastName, email, interest } = parsed;

    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT || 587),
      secure: process.env.SMTP_SECURE === "true",
      auth: {
        user: process.env.AUTH_MAIL || "",
        pass: process.env.AUTH_PASS || "",
      },
    });

    const recipientList =
      process.env.CONTACT_RECIPIENTS || "sricharanrayala24@gmail.com";

    const recipients = recipientList
      .split(",")
      .map((mail) => mail.trim())
      .filter(Boolean)
      .join(",");

    const subject = `New demo request from ${firstName} ${lastName} | Dotportion`;

    const html = `
      <div style="font-family:Arial,Helvetica,sans-serif;background:#f6f6f7;padding:24px;">
        <table style="max-width:640px;margin:0 auto;background:#ffffff;border-radius:12px;overflow:hidden;border:1px solid #e5e7eb;">
          <tr>
            <td style="padding:20px 24px;background:#0b1120;color:#ffffff;">
              <h1 style="font-size:20px;margin:0;">DotPortion — Demo Request</h1>
              <p style="margin:6px 0 0;color:#cbd5e1;font-size:13px;">A new demo request was submitted.</p>
            </td>
          </tr>

          <tr>
            <td style="padding:20px 24px;">
              <h2 style="font-size:16px;margin-bottom:12px;">Contact Details</h2>

              <p><strong>First Name:</strong> ${firstName}</p>
              <p><strong>Last Name:</strong> ${lastName}</p>
              <p><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>

              <h2 style="font-size:16px;margin-top:24px;margin-bottom:8px;">Interest</h2>
              <p style="background:#f9fafb;padding:12px;border-radius:8px;border:1px solid #e5e7eb;white-space:pre-wrap;">
                ${interest}
              </p>
            </td>
          </tr>

          <tr>
            <td style="padding:16px 24px;text-align:center;font-size:12px;color:#6b7280;border-top:1px solid #e5e7eb;">
              This message was generated by the DotPortion Contact Form.
            </td>
          </tr>
        </table>
      </div>
    `;

    const text = `
New demo request:

First Name: ${firstName}
Last Name:  ${lastName}
Email:      ${email}

Interest:
${interest}
    `.trim();

    await transporter.sendMail({
      from: `DotPortion <${process.env.AUTH_MAIL}>`,
      to: recipients,
      subject,
      text,
      html,
    });

    return NextResponse.json({ ok: true });
  } catch (error) {
    if (error instanceof ZodError) {
      return NextResponse.json(
        { ok: false, error: "Validation failed", issues: error.issues },
        { status: 400 }
      );
    }

    console.error("Email sending error:", error);

    return NextResponse.json(
      { ok: false, error: "Internal server error" },
      { status: 500 }
    );
  }
}
